/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SysCtrlX9k2Prime7af3RouteImport } from './routes/sys-ctrl-x9k2-prime-7af3'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KdsRouteImport } from './routes/kds'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SysCtrlX9k2Prime7af3Route = SysCtrlX9k2Prime7af3RouteImport.update({
  id: '/sys-ctrl-x9k2-prime-7af3',
  path: '/sys-ctrl-x9k2-prime-7af3',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KdsRoute = KdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/coupons': typeof CouponsRoute
  '/dashboard': typeof DashboardRoute
  '/kds': typeof KdsRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/sys-ctrl-x9k2-prime-7af3': typeof SysCtrlX9k2Prime7af3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/coupons': typeof CouponsRoute
  '/dashboard': typeof DashboardRoute
  '/kds': typeof KdsRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/sys-ctrl-x9k2-prime-7af3': typeof SysCtrlX9k2Prime7af3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/coupons': typeof CouponsRoute
  '/dashboard': typeof DashboardRoute
  '/kds': typeof KdsRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/sys-ctrl-x9k2-prime-7af3': typeof SysCtrlX9k2Prime7af3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/coupons'
    | '/dashboard'
    | '/kds'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/sys-ctrl-x9k2-prime-7af3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/coupons'
    | '/dashboard'
    | '/kds'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/sys-ctrl-x9k2-prime-7af3'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/coupons'
    | '/dashboard'
    | '/kds'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/sys-ctrl-x9k2-prime-7af3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CouponsRoute: typeof CouponsRoute
  DashboardRoute: typeof DashboardRoute
  KdsRoute: typeof KdsRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
  SysCtrlX9k2Prime7af3Route: typeof SysCtrlX9k2Prime7af3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sys-ctrl-x9k2-prime-7af3': {
      id: '/sys-ctrl-x9k2-prime-7af3'
      path: '/sys-ctrl-x9k2-prime-7af3'
      fullPath: '/sys-ctrl-x9k2-prime-7af3'
      preLoaderRoute: typeof SysCtrlX9k2Prime7af3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kds': {
      id: '/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof KdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CouponsRoute: CouponsRoute,
  DashboardRoute: DashboardRoute,
  KdsRoute: KdsRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
  SysCtrlX9k2Prime7af3Route: SysCtrlX9k2Prime7af3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
